server:
  port: 7001

eureka:
  instance:
    #hostname: localhost #eureka服务端的实例名称 #以前单机版
    hostname: localhost #集群升级版
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # flase 表示自己端就是服务中心 职责就是维护服务实例，不需要检测服务
    fetch-registry: false
    #设置与eureka交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #以前单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7001/eureka/
      # 集群升级版
      #defaultZone: http://eureka7002.com:7002/eureka/

  server:
    #关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000