server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:

      #配置sentinel dashboard地址
      transport:
        dashboard: localhost:8080
        #默认8719端口 假如被占用，依次扫描+1端口，直到找到未被占用端口
        port: 8719
        datasource:
                ds1:
                  nacos:
                    server-addr: localhost:8848
                    dataId: ${spring.application.name}
                    groupId: DEFAULT_GROUP
                    data-type: json
                    rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'
